print("Welcome to tip calculator!")
total = int(input("Enter the amount: $"))
tip = int(input("Please enter percentage of tip: %"))
totalWithTip = round(total * ((tip/100)+1))
print(f"Total with tip is: ${totalWithTip}")
totalPeopleSplit = int(input("How many people you want to split between: "))
print(f"Per person you get :{totalWithTip/totalPeopleSplit}")